apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  namespace: {{ .Values.kubernetes.namespace}}
spec:
  replicas: {{ .Values.kubernetes.replicas}}
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name:
          image:
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.docker.container.port}}
          envFrom:
            - configMapRef:
                name:
          resources:
            limits:
              memory: "{{ .Values.kubernetes.resources.limits.memory}}"
              cpu: "{{ .Values.kubernetes.resources.limits.cpu}}"
            requests:
              memory: "{{ .Values.kubernetes.resources.requests.memory}}"
              cpu: "{{ .Values.kubernetes.resources.requests.cpu}}"
