apiVersion: v1
kind: Service
metadata:
  name:
  namespace: {{ .Values.kubernetes.namespace}}
spec:
  selector:
    app:
  ports:
    - port: {{ .Values.docker.container.port}}
      targetPort: {{ .Values.docker.container.port}}
  type: {{ .Values.kubernetes.service.type}}